import fs from 'node:fs/promises';import path from 'node:path';import {SpreadsheetFile,Workbook} from '@oai/artifact-tool';
const root=path.dirname(new URL(import.meta.url).pathname),task=path.join(root,'task'),renders=path.join(root,'workbook-renders');await fs.mkdir(renders,{recursive:true});const head={fill:'#3A5360',font:{bold:true,color:'#FFFFFF'},wrapText:true},body={wrapText:true,verticalAlignment:'top',borders:{bottom:{style:'thin',color:'#D6E0E5'}}};
function add(book,name,rows,widths){const s=book.worksheets.add(name),r=s.getRangeByIndexes(0,0,rows.length,widths.length);r.values=rows;r.format=body;s.getRangeByIndexes(0,0,1,widths.length).format=head;widths.forEach((w,i)=>s.getRangeByIndexes(0,i,rows.length,1).format.columnWidth=w);r.format.autofitRows();s.freezePanes.freezeRows(1);s.showGridLines=false;}
async function finish(book,label,name){for(const s of book.worksheets.items){const b=await book.render({sheetName:s.name,autoCrop:'all',scale:1.25,format:'png'});await fs.writeFile(path.join(renders,`${label}-${s.name}.png`),new Uint8Array(await b.arrayBuffer()));}const e=await book.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:100},maxChars:5000});await fs.writeFile(path.join(renders,`${label}.errors.ndjson`),e.ndjson);const i=await book.inspect({kind:'sheet,table',include:'id,name,values',tableMaxRows:50,tableMaxCols:8,maxChars:30000});await fs.writeFile(path.join(task,`${name}.inspect.ndjson`),i.ndjson);const f=await SpreadsheetFile.exportXlsx(book);await f.save(path.join(task,name));}
const a=Workbook.create();
add(a,'交付物答案清单',[["交付物名称","固定路径/命名规则","用途","判定方式"],["数据库方案","output/sql/solution.sql","建立窗口约束、事务函数和排队处理对象","由PostgreSQL执行并查询对象"],["构建入口","output/tools/build_delivery.py","装载计划并生成交付结果","连接空数据库执行"],["事务结果","output/results/transaction_outcomes.csv","记录计划事务提交或回滚","按tx_id核对"],["最终窗口","output/results/release_window_final.csv","交接当前窗口账面","按window_id核对"],["排队决定","output/results/pending_window_decisions.csv","说明请求是否进入排程","按pending_id核对"],["活动冲突","output/results/active_overlap_probe.csv","列出最终活动窗口相交对","核对数据行为0"],["边界检查","output/results/range_boundary_probe.csv","记录范围与约束域判断","按probe_id核对"],["触发器信息","output/results/trigger_inventory.csv","确认提交期约束属性","查询pg_trigger"],["输入计数","output/results/source_counts.json","记录本次读取的业务资料","从输入文件复算"],["处理摘要","output/results/handover.json","汇总事务、窗口、请求和冲突","从明细复算"],["批次说明","output/HANDOVER.md","说明执行入口和结果用途","与实际路径核对"]],[32,66,64,56]);
add(a,'固定字段答案',[["交付物或对象","字段路径","正确值","来源与验证"],["处理摘要","status","READY","计划结果匹配且无活动冲突"],["MOVE事务","sqlstate","23P01","自定义提交期约束触发器明确返回"],["活动冲突","数据行数","0","最终活动窗口两两比较"],["目标触发器","deferrable","true","pg_trigger目录"],["目标触发器","initially_deferred","true","pg_trigger目录"],["PW-B3","decision","BLOCKED_OVERLAP","请求时段仍被活动窗口占用"]],[38,54,44,72]);
add(a,'固定集合答案',[["交付物或对象","字段或集合","正确集合","判定方式"],["事务结果","tx_id","TX01_SWAP_LANE_A、TX02_REJECT_OVERLAP_SHIFT、TX03_RELEASE_B_13、TX04_PROMOTE_B_13_BY_TIME、TX05_PROMOTE_A_12_BY_ID、TX06_BLOCK_B_09","集合精确匹配"],["最终窗口","window_id","PROM-PW-A1、PROM-PW-B1、RW-A1、RW-A2、RW-A3、RW-A4、RW-B1、RW-B2、RW-B3、RW-C1","集合精确匹配"],["排队决定","pending_id和decision","PW-A1和PROMOTED、PW-A2和LOST_PRIORITY、PW-B1和PROMOTED、PW-B2和LOST_PRIORITY、PW-B3和BLOCKED_OVERLAP","复合集合精确匹配"],["边界检查","probe_id","CANCELLED、CONTAINED、OTHER_LANE、PARTIAL、TOUCHING","集合精确匹配"],["输入计数","source_counts字段","initial_windows、lanes、pending_requests、planned_transactions","字段集合精确匹配"]],[36,48,128,54]);
add(a,'固定数值答案',[["交付物或对象","字段或位置","正确值","容差","来源与验证"],["source_counts.json","lanes",3,"无容差","release_lanes.csv记录数"],["source_counts.json","initial_windows",8,"无容差","release_windows.csv记录数"],["source_counts.json","pending_requests",5,"无容差","pending_windows.csv记录数"],["source_counts.json","planned_transactions",6,"无容差","transaction_plan.csv记录数"],["handover.json","transaction_rows",6,"无容差","transaction_outcomes.csv记录数"],["handover.json","window_rows",10,"无容差","release_window_final.csv记录数"],["handover.json","pending_rows",5,"无容差","pending_window_decisions.csv记录数"],["handover.json","active_overlap_pairs",0,"无容差","active_overlap_probe.csv数据行数"]],[36,50,24,26,64]);
add(a,'允许变体答案',[["对象","允许变化","不可变化","判定方式"],["数据库对象","函数与中间对象名称可以采用等价命名","提交期约束、事务回滚、通道锁和排队语义不能变化","执行后查询行为"],["事务实现","SQL语句拆分和内部事务封装可以变化","计划顺序、结果和失败后状态不能变化","按tx_id核对"],["CSV文件","行序可以变化","表头、业务主键和字段值不能变化","按业务主键排序后比较"],["JSON文件","键序、缩进和空白可以变化","状态、计数和字段值不能变化","解析JSON后比较"],["批次说明","段落和措辞可以变化","输入目录、执行入口和结果路径不能缺失","定位路径并核对内容"]],[34,82,90,58]);await finish(a,'关键标准答案','关键标准答案.xlsx');
const s=Workbook.create();add(s,'任务规格',[["模块","规格内容"],["任务ID","postgres_release_window_processing"],["主软件","PostgreSQL Client"],["辅助工具","psql、PowerShell7、Python3.12、UTF-8文本编辑器、CSV查看器和JSON查看器"],["输入来源","边缘发布组导出的虚构通道、窗口、排队请求、事务计划、窗口合同和SQL骨架"],["输入获取方式","从输入数据包解压到本地只读目录"],["原始输入文件","input_data/data中的release_lanes.csv、release_windows.csv和pending_windows.csv，contracts中的transaction_plan.csv和window_contract.json，starter/release_window_starter.sql及README.md"],["目标输出文件","output/sql数据库方案、output/tools构建入口、output/results结构化结果和output/HANDOVER.md"],["核心操作链","输入核对→范围建模→提交期冲突约束→计划事务→排队处理→边界检查→批次汇总"],["冲突口径","同一lane_id的ACTIVE窗口使用左闭右开tstzrange判断相交，提交期仍相交时返回SQLSTATE23P01并回滚"],["计划口径","按transaction_plan.csv顺序处理SWAP、MOVE、CANCEL、PROMOTE和ASSESS，失败事务不得留下部分修改"],["排队口径","锁定release_lane后按priority降序、requested_at升序和pending_id升序决定，晋升窗口保留source_pending_id"],["边界口径","端点相接、跨通道和CANCELLED窗口不进入冲突，部分相交与包含关系进入冲突"],["完成条件","空数据库可执行方案并生成全部交付物，计划结果符合expected，活动冲突为0，处理摘要状态为READY"],["可验证点","输入主键集合、范围属性、触发器延期属性、事务结果、回滚状态、排队决定、来源关系、活动冲突和摘要计数"],["不适合作为评分点的内容","SQL排版、数据库对象名称、等价查询结构、CSV行序、JSON键序、临时数据库名称、文本编辑器选择和说明措辞"]],[34,136]);await finish(s,'任务规格转化','任务规格转化.xlsx');

